# Generated by Django 5.0.6 on 2024-06-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_member_user_member_name_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
