# Generated by Django 5.0.6 on 2024-06-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='job_title',
            new_name='role',
        ),
    ]
