# Generated by Django 5.0.6 on 2024-06-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_member_name_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
