# Generated by Django 5.0.6 on 2024-06-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
